# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
      LoginBundle\Entity\User:
        algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
      in_memory:
        memory: ~
      db_provider:
        entity:
          class: LoginBundle:User
          property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            # activate different ways to authenticate
            anonymous: ~

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

            form_login: 
              login_path: login
              check_path: login
            

    access_control:
        - { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/danke$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/admin, roles: ROLE_USER_IP, ip: 127.0.0.1 }
#        - { path: ^/admin, roles: ROLE_USER_HOST, host: symfony\.com$ }
#        - { path: ^/admin, roles: ROLE_USER_METHOD, methods: [POST, PUT] }
#        - { path: ^/admin, roles: ROLE_USER }
            
            